### ISSUE TITLE
Dashboard tasks icon dark in dark theme

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#1718]
This
https://github.com/nextcloud/tasks/blob/6b6aec510c7b95b37fcd2b6b537ef3babf99bb44/src/css/dashboard.scss#L5-L7
should read
```css
 body.theme--dark .icon-tasks { 
 	background-image: url(./../../img/tasks.svg); 
 } 
```
