### ISSUE TITLE
Settings label not aligned to app-navigation-entry

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#1719]
Until https://github.com/nextcloud/nextcloud-vue/issues/2138 is done, we should provide a hot-fix here.
```css
#app-settings-header .settings-button {
	padding-left: 50px;
}
```
