### ISSUE TITLE
fix: adjust task body height to new default clickable area

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/tasks#2772]
This should adjust the task body height to the new value:

```css
/* main-9SmC4sMV.chunk.css | https://nextcloud.rschluessler.com/custom_apps/tasks/css/main-9SmC4sMV.chunk.css */

.task-item__body[data-v-51d5d678] {
  /* height: 44px; */
  height: var(--default-clickable-area);
}

.task-checkbox[data-v-f2d69f7e] {
  /* height: 44px; */
  /* width: 44px; */
  height: var(--default-clickable-area);
  width: var(--default-clickable-area);
}

.task-item__body .task-body__info .summary span[data-v-51d5d678] {
  /* line-height: 24px; */
  line-height: var(--default-clickable-area);
}

.task-item__body .task-body__info .summary[data-v-51d5d678] {
  /* padding: 10px 10px 10px 0; */
}

.task-checkbox input[type="checkbox"] + label[data-v-f2d69f7e] {
  /* height: 44px; */
  /* width: 44px; */
  /* padding: 11px; */
  height: var(--default-clickable-area);
  width: var(--default-clickable-area);
  padding: 6px;
}
```
